### ISSUE TITLE
Přebíjení zálohovacího kondenzátoru

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/GPS02#3]
Zálohovací kondenzátor je nabíjen na hodnotu 3.07 V. Maximální přípustná hodnota napětí na kondezátoru však je 2.7 V 

Příčinou přebíjení je fakt, že kondenzátor je nabíjen přes shottkyho diodu BAS85, která má napěťový úbytek pouze 0.2V 

![image](https://user-images.githubusercontent.com/1194177/86464274-7149dc80-bd2f-11ea-9ce7-d94c7dd884de.png)

K odstranění tohoto problému je nutné použít nějakou normální křemíkovou diodu s napěťovým úbytkem alespoň 0.5V.

**Comment by ChroustJan** [comment]
Tak už víme, proč tam byla ta jiná dioda, která se ti nezdála.

**Comment by ChroustJan** [comment]
Aplikována dioda M4
