### ISSUE TITLE
Upravit otvor pro SMA konektor

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/GPS02#5]
Upravit otvory na SMA dle starých MLAB knihoven.

Viz issue #1

**Comment by kaklik** [comment]
Proč? Teď máme stejně MCX..

**Comment by ChroustJan** [comment]
Považuji za rozumné mít tu možnost. Nevychází to o chlup. Kicad má pro nás nevyhovující knihovnu.

**Comment by ChroustJan** [comment]
Provedeno.
